# Generated by Django 2.1.5 on 2019-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_parkingspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
