# Generated by Django 2.1.5 on 2019-01-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parking_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_id', models.ForeignKey(on_delete='CASCADE', related_name='parking_spot', to='parking.Parking')),
            ],
        ),
    ]
